DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS attempts;
DROP TABLE IF EXISTS compRate;
DROP TABLE IF EXISTS requests;
DROP TABLE IF EXISTS seasonFlux;

CREATE TABLE users (
  email TEXT PRIMARY KEY NOT NULL,
  password TEXT NOT NULL,
  first TEXT NOT NULL,
  last TEXT NOT NULL,
  company TEXT NOT NULL,
  addr TEXT NOT NULL,
  city TEXT NOT NULL,
  state TEXT NOT NULL,
  zipcode TEXT NOT NULL,
  attempts INTEGER NOT NULL DEFAULT 0,
  logged INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE attempts (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  email TEXT NOT NULL,
  password TEXT NOT NULL,
  datestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  result INTEGER NOT NULL,
  location TEXT NOT NULL
);

CREATE TABLE compRate (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  company TEXT NOT NULL,
  month INTEGER NOT NULL,
  year INTEGER NOT NULL,
  price REAL NOT NULL
);

CREATE TABLE requests (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  email TEXT NOT NULL,
  gallons INTEGER NOT NULL,
  deliv_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  price REAL NOT NULL,
  transport INTEGER NOT NULL,
  discLvl TEXT NOT NULL,
  percDisc REAL NOT NULL,
  compPrice REAL NOT NULL,
  total REAL NOT NULL,
  FOREIGN KEY (email) REFERENCES users (email)
);

CREATE TABLE seasonFlux (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  season TEXT NOT NULL,
  percInc REAL NOT NULL
);